#' Gather Loser Playoff Bracket
#'
#' Given a league ID, get the loser playoff bracket for the league.
#'
#' @return Returns a dataframe containing playoff information for the loser bracket.
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, December 2021
#' @keywords league playoff loser
#' @importFrom httr GET content
#' @importFrom jsonlite fromJSON
#' @export
#' @examples
#' get_loser_playoff_bracket(688281863499907072)
#'
#' @param league_id League ID generated by Sleeper (integer)
#'
get_loser_playoff_bracket <- function(league_id) {
  return(fromJSON(content(GET(paste0("https://api.sleeper.app/v1/league/", league_id, "/losers_bracket")), as = "text")))
}