#' Gather Draft Pick Trades
#'
#' Given a draft ID, gather draft pick trades for that draft.
#'
#' @return Returns a list containing information about the draft pick trade(s).
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, December 2021
#' @keywords draft pick trades
#' @importFrom httr GET content
#' @importFrom jsonlite fromJSON
#' @export
#' @examples
#' get_draft_pick_trades(688281872463106048)
#'
#' @param draft_id Draft ID generated by Sleeper (integer)
#'
get_draft_pick_trades <- function(draft_id) {
  return(fromJSON(content(GET(paste0("https://api.sleeper.app/v1/draft/", draft_id, "/traded_picks")), as = "text")))
}