#' Gather User Data for League
#'
#' Given a league ID, grab the data concerning each user. This includes information about the users' mascot,
#' display name, avatar, if they are an owner, if they are a bot, and more.
#'
#' @return Returns a data frame containing information about the users in the league.
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, September 2021
#' @keywords league users
#' @importFrom httr GET
#' @importFrom jsonlite content fromJSON
#' @export
#' @examples
#' get_league_users_data(688281863499907072)
#'
#' @param league_id League ID generated by Sleeper (integer)
#'
get_league_users_data <- function(league_id) {
  return(fromJSON(content(GET(paste0("https://api.sleeper.app/v1/league/", league_id, "/users")), as = "text")))
}
