#' Gather League Data
#'
#' Given a league ID, grab the data for that league. Includes roster positions, season type, if it is in
#' season, and more.
#'
#' @return Returns a list containing information about the league.
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, September 2021
#' @keywords user users
#' @importFrom httr GET content
#' @importFrom jsonlite fromJSON
#' @export
#' @examples
#' get_league_data(688281863499907072)
#'
#' @param league_id League ID generated by Sleeper (integer)
#'
get_league <- function(league_id) {
  return(fromJSON(content(GET(paste0("https://api.sleeper.app/v1/league/", league_id)), as = "text")))
}