#' Gather User Draft Information
#'
#' Given a user ID, sport abbreviation, and season number, gather draft information for that selection.
#'
#' @return Returns a dataframe containing information about the draft(s).
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, December 2021
#' @keywords user draft
#' @importFrom httr GET content
#' @importFrom jsonlite fromJSON
#' @export
#' @examples
#' get_user_drafts(688556535013502976, "nfl", 2021)
#'
#' @param user_id User ID generated by Sleeper (integer)
#' @param sport Sport that you would like to query ("nfl" only supported currently) (string)
#' @param season Season that you would like to select (integer)
#'
get_user_drafts <- function(user_id, sport, season) {
  return(fromJSON(content(GET(paste0("https://api.sleeper.app/v1/user/", user_id, "/drafts/", sport, "/", season)), as = "text")))
}