#' Gather League Trades
#'
#' Given a league ID, grab the trades that have occured.
#'
#' @return Returns a list containing trades.
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, September 2021
#' @keywords league trades
#' @importFrom httr GET content
#' @importFrom jsonlite fromJSON
#' @export
#' @examples
#' get_traded_picks(688281863499907072)
#'
#' @param league_id League ID generated by Sleeper (integer)
#'
get_traded_picks <- function(league_id) {
  return(fromJSON(content(GET(paste0("https://api.sleeper.app/v1/league/", league_id, "/traded_picks")), as = "text")))
}