#' Generate Main Data
#'
#' Given the league ID, generate a main data set that can be used for generating quick
#' insights.
#'
#' @return Returns a data frame containing roster, league user, and overall league information. 
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, December 2023
#' @keywords roster league user full main
#' @importFrom dplyr left_join rename case_when
#' @export
#' @examples
#' \dontrun{get_main_data(688281863499907072)}
#'
#' @param league_id League ID generated by Sleeper (numeric).
#'
get_main_data <- function(league_id) {
  # Query league data first to see if league ID is valid
  league_data <- suppressMessages(get_league(league_id))
  if(is.null(league_data)) {
    # If NULL, inform user and return nothing
    message("League ID did not return any results. Did you enter the league ID correctly?")
  } else { 
    # Query data with league ID to get roster and league user data
    roster_data <- get_rosters(league_id)
    league_user_data <- get_league_users(league_id)
    # Remove league ID from league user data since already present in roster data (or else will have duplicates)
    league_user_data$league_id <- NULL
    # Rename avatar column since same naming convention present in other data that will be joined to it
    league_data <- dplyr::rename(league_data, "avatar_league" = "avatar")
    # Join roster data to league user data
    master_df_pre <- dplyr::left_join(roster_data, 
                                     league_user_data, 
                                     by = c("owner_id" = "user_id"))
    # Join previous data frame to league data data frame
    master_df <- dplyr::left_join(master_df_pre, 
                                  league_data,
                                  by = "league_id")
    # Add total fantasy points (for and against) columns
    master_df$fpts_total <- master_df$fpts + master_df$fpts_decimal / 100
    master_df$fpts_against_total <- master_df$fpts_against + master_df$fpts_against_decimal / 100
    # Add streak ranking column
    master_df$streak_ranking <- ifelse(substr(master_df$streak, start = 2, stop = 2) == "L", 
                                  -as.numeric(substr(master_df$streak, start = 1, stop = 1)),
                                  as.numeric(substr(master_df$streak, start = 1, stop = 1)))
    # Add division names column (currently only goes up to four)
    master_df$division_name <- dplyr::case_when(
      master_df$division == 1 ~ master_df$division_1,
      master_df$division == 2 ~ master_df$division_2,
      master_df$division == 3 ~ master_df$division_3,
      master_df$division == 4 ~ master_df$division_4,
      TRUE ~ as.character(master_df$division))
    # Add ranking based on wins/losses and fantasy points for
    master_df$rank_fpts <- rank(-master_df$wins * 400 + master_df$losses * 400 - master_df$fpts_total)
    # Return full data frame
    return(master_df)
  }
}