#' Gather Draft Information
#'
#' Given a draft ID, gather draft information for selection.
#'
#' @return Returns a list containing information about the draft.
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, December 2021
#' @keywords draft
#' @importFrom httr GET content
#' @importFrom jsonlite fromJSON
#' @export
#' @examples
#' get_draft(688281872463106048)
#'
#' @param draft_id Draft ID generated by Sleeper (integer)
#'
get_draft <- function(draft_id) {
  return(fromJSON(content(GET(paste0("https://api.sleeper.app/v1/draft/", draft_id)), as = "text")))
}