#' Gather Roster Data for League
#'
#' Given a league ID, grab the data concerning each roster in that league. This includes information with the 
#' roster wins, losses, ties, fantasy points, and more.
#'
#' @return Returns a data frame containing information about the rosters in the league.
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, September 2021
#' @keywords league users rosters
#' @importFrom httr GET content
#' @importFrom jsonlite fromJSON
#' @export
#' @examples
#' get_roster_data(688281863499907072)
#'
#' @param league_id League ID generated by Sleeper (integer)
#'
get_roster_data <- function(league_id) {
  return(fromJSON(content(GET(paste0("https://api.sleeper.app/v1/league/", league_id, "/rosters")), as = "text")))
}
