#' Gather User Data
#'
#' Given a user ID, grab the data concerning that particular user. This includes username, user ID, display 
#' name, and more.
#'
#' @return Returns a list containing information about the user.
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, September 2021
#' @keywords user users
#' @importFrom httr GET content
#' @importFrom jsonlite fromJSON
#' @export
#' @examples
#' get_user(688556535013502976)
#'
#' @param user_id User ID generated by Sleeper (integer)
#'
get_user <- function(user_id) {
  return(fromJSON(content(GET(paste0("https://api.sleeper.app/v1/user/", user_id)), as = "text")))
}