#' Gather Leagues for User
#'
#' Given a user ID and optional sport and season, grab the league data concerning that particular user. 
#' This includes total rosters, scoring settings, roster positions, and more.
#'
#' @return Returns a data frame containing information about the user.
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, September 2021
#' @keywords league user
#' @importFrom httr GET content
#' @importFrom jsonlite fromJSON
#' @export
#' @examples
#' get_user_leagues(688556535013502976)
#' get_user_leagues(688556535013502976, sport = "nfl", season = "2021")
#'
#' @param user_id User ID generated by Sleeper (integer)
#' @param sport Sport for league information (string)
#' @param season Season for league information (string)
#'
get_user_leagues <- function(user_id, sport = "nfl", season = substr(Sys.Date(), start = 1, stop = 4)) {
  return(fromJSON(content(GET(paste0("https://api.sleeper.app/v1/user/", user_id, "/leagues/", sport, "/", season)), as = "text")))
}