#' Gather League Transactions for Specific Round
#'
#' Given a league ID and round, grab the transaction data concerning that particular league.
#' This includes adds or drops, whether it was a free agent or a waiver, notes, and more.
#'
#' @return Returns a data frame containing information about the round of transactions for that league.
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, September 2021
#' @keywords transactions league
#' @importFrom httr GET content
#' @importFrom jsonlite fromJSON
#' @export
#' @examples
#' get_transaction_data(688281863499907072, 2)
#'
#' @param league_id League ID generated by Sleeper (integer)
#' @param round round of transactions to gather (can also be thought of as week depending on when your league processes transactions) (integer)
#'
get_transaction_data <- function(league_id, round) {
  return(fromJSON(content(GET(paste0("https://api.sleeper.app/v1/league/", league_id, "/transactions/", round)), as = "text")))
}

