#' Gather Draft Picks
#'
#' Given a draft ID, gather draft picks (along with other metadata concerning the picks).
#'
#' @return Returns a dataframe containing information about the draft picks.
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, December 2021
#' @keywords draft picks
#' @importFrom httr GET content
#' @importFrom jsonlite fromJSON
#' @export
#' @examples
#' get_draft_picks(688281872463106048)
#'
#' @param draft_id Draft ID generated by Sleeper (integer)
#'
get_draft_picks <- function(draft_id) {
  return(fromJSON(content(GET(paste0("https://api.sleeper.app/v1/draft/", draft_id, "/picks")), as = "text")))
}