#' Gather League Draft Information
#'
#' Given a league ID, gather draft information for that league.
#'
#' @return Returns a data frame containing draft information for that league.
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, December 2021
#' @keywords draft league
#' @importFrom httr GET content
#' @importFrom jsonlite fromJSON
#' @export
#' @examples
#' get_league_drafts(688281863499907072)
#'
#' @param league_id League ID generated by Sleeper (numeric or character)
#'
get_league_drafts <- function(league_id) {
  return(fromJSON(content(GET(paste0("https://api.sleeper.app/v1/league/", league_id, "/drafts")), as = "text")))
}