#' Plot League Fantasy Points Against by User
#'
#' Given a league ID, plot the number of fantasy points scored against so far by each user. Note that this 
#' plot was created specifically with a NFL fantasy league, so results may vary when Sleeper decides to 
#' incorporate other fantasy sports data.  
#'
#' @return Returns a bar chart showing fantasy points against by each user.
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, September 2021
#' @keywords standings plot fantasy points against
#' @importFrom httr GET content
#' @importFrom jsonlite fromJSON
#' @import dplyr
#' @import ggplot2
#' @export
#' @examples
#' plot_fpts_against(688281863499907072, "Fantasy Points Against by User")
#'
#' @param league_id League ID generated by Sleeper (integer)
#' @param title Optional title of the plot (string)
#' @param subtitle Optional subtitle of the plot (string)
#'
plot_fpts_against <- function(league_id, title = "", subtitle = "") {
  rosters <- get_rosters(league_id)
  league_users <- get_league_users(league_id)
  team_stats <- rosters$settings %>%
    select(wins, ties, losses, fpts, fpts_against, division) %>%
    bind_cols(data.frame(owner_id = rosters$owner_id))
  full_data <- league_users %>%
    select(user_id, display_name) %>%
    left_join(team_stats, by = c("user_id" = "owner_id")) %>%
    filter(is.na(wins) == FALSE)
  p <- ggplot(full_data, aes(x = reorder(display_name, fpts_against), y = fpts_against, fill = fpts_against)) +
    geom_col(color = "black", position = "dodge") +
    geom_text(aes(label = fpts_against), position = position_stack(vjust = 0.5)) +
    ggtitle(title,
            subtitle = subtitle) +
    labs(x = "Name", y = "Fantasy Points Against") + 
    theme(plot.title = element_text(hjust = 0.5, face = "bold"),
          plot.subtitle = element_text(hjust = 0.5),
          axis.title = element_text(face = "bold"),
          legend.position = "none",
          axis.text.x = element_text(angle = 45)) +
    scale_fill_continuous(low = "green", high = "red")
  return(p)
}