#' Plot League Dashboard
#'
#' Given the league ID, generate a dashboard with various
#' plots/tables of the current league.
#'
#' @return Returns a dashboard of current league state.
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, January 2024
#' @keywords league dashboard plot
#' @importFrom dplyr left_join
#' @importFrom plotly plot_ly layout subplot
#' @importFrom stats reorder
#' @importFrom scales comma
#' @export
#' @examples
#' \dontrun{plot_league_dashboard(688281863499907072)}
#'
#' @param league_id League ID generated by Sleeper (numeric).
#'
plot_league_dashboard <- function(league_id) {
    # Obtain master plotting data frame from league ID
    master_df <- plot_generate_master_data(league_id)
    # If nothing is returned for master data frame, return nothing
    # A message already informs user of error in plot_generate_master_data
    # If data frame returned, store certain strings in variables
    league_name <- master_df$name[1]
    league_status <- master_df$status[1]
    league_sport <- toupper(master_df$sport[1])
    leauge_id <- master_df$league_id[1]

    fig <- plotly::plot_ly(
            type = "table",
            header = list(
                values = c("Test"),
                align = c("center"),
                fill = list(color = c("#01092e")),
                font = list(color = "white")
            )
            )
    fig2 <- plotly::plot_ly(
            type = "table",
            header = list(
                values = c("Test2"),
                align = c("center"),
                fill = list(color = c("#01092e")),
                font = list(color = "white")
            )
            )

    plotly::subplot(fig2)
 
}