#' Plot League Win/Loss and Net Fantasy Points
#'
#' Given a league ID, plot the standings so far for the league. This includes wins compared to losses and 
#' fantasy point differentials. Note that this plot was created specifically with a NFL fantasy league, so
#' results may vary when Sleeper decides to incorporate other fantasy sports data.  
#'
#' @return Returns a plot showing net wins and losses colored by fantasy point differentials.
#' @author Nick Bultman, \email{njbultman74@@gmail.com}, September 2021
#' @keywords standings plot wins losses points
#' @importFrom httr GET content
#' @importFrom jsonlite fromJSON
#' @import dplyr
#' @import ggplot2
#' @export
#' @examples
#' plot_wl_nfp(688281863499907072, "Net Wins/Losses (Wins - Losses), Colored by FPTS Differential (Points For - Points Against)")
#'
#' @param league_id League ID generated by Sleeper (integer)
#' @param title Optional title of the plot (string)
#' @param subtitle Optional subtitle of the plot (string)
#'
plot_wl_nfp <- function(league_id, title = "", subtitle = "") {
  rosters <- get_roster_data(league_id)
  league_users <- get_league_users_data(league_id)
  team_stats <- rosters$settings %>%
    select(wins, ties, losses, fpts, fpts_against, division) %>%
    bind_cols(data.frame(owner_id = rosters$owner_id))
  full_data <- league_users %>%
    select(user_id, display_name) %>%
    left_join(team_stats, by = c("user_id" = "owner_id")) %>%
    filter(is.na(wins) == FALSE) %>%
    mutate(fpts_net = fpts - fpts_against,
           wins_losses_net = wins - losses,
           ordering = ifelse(wins_losses_net > 0, fpts_net * wins_losses_net, ifelse(wins_losses_net < 0, fpts_net * -wins_losses_net, fpts_net)))
  p <- ggplot(full_data, aes(x = reorder(display_name, -ordering), y = wins_losses_net, fill = fpts_net)) +
    geom_col(color = "black", position = "dodge") +
    geom_text(aes(label = fpts_net), position = position_stack(vjust = 0.5)) +
    ggtitle(title,
            subtitle = subtitle) +
    labs(x = "Name", y = "Net Wins & Losses", fill = "Net FPTS") +
    theme(plot.title = element_text(hjust = 0.5, face = "bold"),
          plot.subtitle = element_text(hjust = 0.5),
          axis.title = element_text(face = "bold"),
          legend.position = "none",
          axis.text.x = element_text(angle = 45)) +
    scale_fill_continuous(low = "red", high = "green")
  return(p)
}
